# Change these first
owner: Fernandoguidet # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Mainsoft
    url: https://mainsoft.cl
    icono: https://mainsoft.cl/wp-content/uploads/2022/10/cropped-icon-fav-2-32x32.jpg
 - name: Itaú 
    url: https://banco.itau.cl
    #icono: https://d1dzq2r60kxox4.cloudfront.net/uploads/bb9193d2-d4b8-4f76-bcf2-d6e935663c0b/original/header_logo.svg
 - name: BCI 
    url: https://www.bci.cl
    #icono: https://cdn3.bci.cl/uploads/e682d72b-13b1-49a3-93ce-20f6252e1d17/original/logo_bci_negro.svg
 - name: Scotiabank Chile 
    url: https://www.scotiabankchile.cl
    #icono: https://scotiabankfiles.azureedge.net/scotiabank-chile/logo/logo-scotia-red-tm.svg
- name: Banco Chile 
    url: https://portales.bancochile.cl
    #icono: https://portales.bancochile.cl/uploads/000/051/449/946eae2e-f803-4b02-ac99-f180633c9a6c/original/Banco_de_Chile.svg
- name: Movistar Chile 
    url: https://ww2.movistar.cl
    #icono: https://pbs.twimg.com/profile_images/1666927488327450626/VXigWqv-_400x400.jpg
- name: Falabella 
    url: https://tienda.falabella.com
    #icono: https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Falabella_Icono.svg/401px-Falabella_Icono.svg.png?20170504032206

    

assignees: # Users to assign downtime issues (optional)
  - FernandoGuidet
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  theme: ocean
  logoUrl: https://mainsoft.cl/wp-content/uploads/2022/10/logo-mainsoft.png
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "**Status Page** es una página de estado y Servicio de monitoreo de sitios web"
  introMessage: Es diferente de los sistemas de página de estado tradicionales, verifica el estado de salud del sitio web cada 5 minutos, envia notificaciones a canales como Slack, Telegram, Discord, Correo electrónico y SMS
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
